In [1]:
import os 
import pandas as pd
import numpy as np 
from sklearn.metrics import accuracy_score, roc_curve, confusion_matrix, classification_report, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.model_selection import GridSearchCV
import sys 
from sklearn.model_selection import learning_curve
from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler

In [2]:
# display test scores and return result string and indexes of false samples
def display_test_scores(test, pred):
    str_out = ""
    str_out += ("TEST SCORES\n")
    str_out += ("\n")

    #print accuracy
    accuracy = accuracy_score(test, pred)
    str_out += ("ACCURACY: {:.4f}\n".format(accuracy))
    str_out += ("\n")

  
    #print confusion matrix
    str_out += ("CONFUSION MATRIX:\n")
    conf_mat = confusion_matrix(test, pred)
    str_out += ("{}".format(conf_mat))
    str_out += ("\n")
    str_out += ("\n")

    #print FP, FN
    str_out += ("FALSE POSITIVES:\n")
    fp = conf_mat[1][0]
    pos_labels = conf_mat[1][0]+conf_mat[1][1]
    str_out += ("{} out of {} positive labels ({:.4f}%)\n".format(fp, pos_labels,fp/pos_labels))
    str_out += ("\n")

    str_out += ("FALSE NEGATIVES:\n")
    fn = conf_mat[0][1]
    neg_labels = conf_mat[0][1]+conf_mat[0][0]
    str_out += ("{} out of {} negative labels ({:.4f}%)\n".format(fn, neg_labels, fn/neg_labels))
    str_out += ("\n")

    #print classification report
    str_out += ("PRECISION, RECALL, F1 scores:\n")
    str_out += ("{}".format(classification_report(test, pred)))
    
    false_indexes = np.where(test != pred)
    return str_out, false_indexes

In [3]:
################ rldd_normalized_scaled dataset ###################
df_original = pd.read_pickle('../input/rlddandmerged/rldd_normalized_scaled.pkl')

X = df_original.loc[:, ["n_EAR", 
                    "n_MAR", "n_MOE", "n_EC",
                    "n_LEB", "n_SOP", "PERCLOS", "CLOSENESS"]]



### encode y values to multiclass ###
y = df_original.loc[:, "DROWSINESS"]
y = y.map({0: 0, 0.5: 1, 1:2})
df_original.loc[:, "DROWSINESS"] = y

y_f = df_original.loc[:, "DROWSINESS"]


X_train, X_test, y_train, y_test = train_test_split(X, y_f, test_size = 0.2, stratify = y)

In [4]:
# cross-validation with 5 splits
cv = StratifiedShuffleSplit(n_splits=5, random_state = 42)

#Importing XGBM Classifier 
from xgboost import XGBClassifier

#creating an extreme Gradient boosting instance
xgb = XGBClassifier(random_state=0, tree_method = "gpu_hist")

# parameters 
parameters = {
                "n_estimators": [100, 200, 300],
                "max_depth": [7, 9, 11],
                "subsample": [0.3, 0.5, 0.7, 0.9, 1]            
}

In [5]:
# grid search for parameters
grid = GridSearchCV(estimator=xgb, param_grid=parameters, cv=cv, n_jobs=-1)
grid.fit(X_train, y_train)

# print best scores
print("The best parameters are %s with a score of %0.4f"
      % (grid.best_params_, grid.best_score_))

# prediction results
y_pred = grid.predict(X_test)

# print accuracy metrics
results, false = display_test_scores(y_test, y_pred)
print(results)

/opt/conda/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py:706: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning


The best parameters are {'max_depth': 11, 'n_estimators': 300, 'subsample': 0.7} with a score of 0.8778
TEST SCORES

ACCURACY: 0.8785

CONFUSION MATRIX:
[[179565  10881   8438]
 [ 18150 168145  12025]
 [ 12889  10515 179489]]

FALSE POSITIVES:
18150 out of 186295 positive labels (0.0974%)

FALSE NEGATIVES:
10881 out of 190446 negative labels (0.0571%)

PRECISION, RECALL, F1 scores:
              precision    recall  f1-score   support

           0       0.85      0.90      0.88    198884
           1       0.89      0.85      0.87    198320
           2       0.90      0.88      0.89    202893

    accuracy                           0.88    600097
   macro avg       0.88      0.88      0.88    600097
weighted avg       0.88      0.88      0.88    600097

